"""
===============================================================================
SEEDER TEMPLATE
Auto-generated by AUTO_SEEDER_GENERATOR
===============================================================================
Feature: {feature}
Table: {table_name}
Generated: {timestamp}
===============================================================================

Run with:
    python seeders/{table_name}_seeder.py --count 100
    python seeders/{table_name}_seeder.py --count 100 --sync
    python seeders/{table_name}_seeder.py --count 100 --clear

Options:
    --count N     Number of rows to generate (default: 100)
    --clear       Clear existing data before seeding
    --sync        Sync to remote Supabase after seeding
    --db-url URL  Override database connection URL
    --batch-size  Batch size for large inserts (default: 1000)

===============================================================================
"""

import argparse
import asyncio
import os
import random
import uuid
from datetime import datetime, timedelta
from decimal import Decimal
from typing import Any, Dict, List, Optional

import asyncpg
from faker import Faker

# =============================================================================
# CONFIGURATION
# =============================================================================

TABLE_NAME = "{table_name}"
DEFAULT_COUNT = 100
DEFAULT_BATCH_SIZE = 1000

# Database URL from environment or default
DATABASE_URL = os.getenv(
    "ENGINE_DATABASE_URL",
    "postgresql://engine:engine@localhost:5432/{project}_engine"
)

# Initialize Faker with locale
fake = Faker(['en_US'])
Faker.seed(None)  # Random seed for variety


# =============================================================================
# DATA GENERATORS
# =============================================================================
# Each function generates a realistic value for its column.
# Customize these based on your domain requirements.

def generate_id() -> str:
    """Generate UUID primary key."""
    return str(uuid.uuid4())


# --- TEXT COLUMNS ---

def generate_title() -> str:
    """Generate a title (e.g., movie title, article title)."""
    patterns = [
        lambda: f"{fake.word().title()} {fake.word().title()}",
        lambda: f"The {fake.word().title()} of {fake.word().title()}",
        lambda: f"{fake.first_name()}'s {fake.word().title()}",
        lambda: f"{fake.word().title()}: {fake.word().title()} {fake.word().title()}",
    ]
    return random.choice(patterns)()


def generate_description() -> str:
    """Generate a description paragraph."""
    return fake.paragraph(nb_sentences=3)


def generate_name() -> str:
    """Generate a person or entity name."""
    return fake.name()


def generate_email() -> str:
    """Generate an email address."""
    return fake.email()


def generate_url() -> str:
    """Generate a URL."""
    return fake.url()


def generate_image_url(width: int = 300, height: int = 200) -> str:
    """Generate a placeholder image URL."""
    seed = fake.random_int(1, 10000)
    return f"https://picsum.photos/seed/{seed}/{width}/{height}"


def generate_phone() -> str:
    """Generate a phone number."""
    return fake.phone_number()


def generate_address() -> str:
    """Generate a full address."""
    return fake.address()


def generate_city() -> str:
    """Generate a city name."""
    return fake.city()


def generate_country() -> str:
    """Generate a country name."""
    return fake.country()


# --- NUMERIC COLUMNS ---

def generate_integer(min_val: int = 0, max_val: int = 1000) -> int:
    """Generate an integer in range."""
    return fake.random_int(min=min_val, max=max_val)


def generate_decimal(
    left_digits: int = 5,
    right_digits: int = 2,
    min_value: float = 0,
    max_value: float = 99999
) -> Decimal:
    """Generate a decimal number."""
    return Decimal(str(round(random.uniform(min_value, max_value), right_digits)))


def generate_rating(min_val: float = 0, max_val: float = 10) -> Decimal:
    """Generate a rating value."""
    return Decimal(str(round(random.uniform(min_val, max_val), 1)))


def generate_price(min_val: float = 0.99, max_val: float = 999.99) -> Decimal:
    """Generate a price value."""
    return Decimal(str(round(random.uniform(min_val, max_val), 2)))


def generate_percentage() -> Decimal:
    """Generate a percentage (0-100)."""
    return Decimal(str(round(random.uniform(0, 100), 2)))


# --- BOOLEAN COLUMNS ---

def generate_boolean(probability: float = 0.5) -> bool:
    """Generate a boolean with given probability of True."""
    return random.random() < probability


# --- DATE/TIME COLUMNS ---

def generate_past_date(years: int = 10) -> datetime:
    """Generate a date in the past N years."""
    return fake.date_between(start_date=f'-{years}y', end_date='today')


def generate_future_date(days: int = 365) -> datetime:
    """Generate a date in the next N days."""
    return fake.date_between(start_date='today', end_date=f'+{days}d')


def generate_datetime_this_year() -> datetime:
    """Generate a datetime within this year."""
    return fake.date_time_this_year()


def generate_created_at() -> datetime:
    """Generate created_at timestamp."""
    return fake.date_time_between(start_date='-1y', end_date='now')


def generate_updated_at(created_at: datetime) -> datetime:
    """Generate updated_at timestamp (after created_at)."""
    return fake.date_time_between(start_date=created_at, end_date='now')


# --- ENUM/STATUS COLUMNS ---

def generate_status(options: List[str] = None) -> str:
    """Generate a status from options."""
    if options is None:
        options = ['active', 'inactive', 'pending']
    return random.choice(options)


def generate_enum(options: List[str]) -> str:
    """Generate a value from enum options."""
    return random.choice(options)


# --- JSON COLUMNS ---

def generate_metadata() -> dict:
    """Generate metadata JSON."""
    return {
        "source": fake.word(),
        "version": f"{fake.random_int(1, 5)}.{fake.random_int(0, 9)}",
        "tags": [fake.word() for _ in range(random.randint(1, 5))],
    }


def generate_settings() -> dict:
    """Generate settings JSON."""
    return {
        "notifications": generate_boolean(0.8),
        "theme": random.choice(["light", "dark", "system"]),
        "language": random.choice(["en", "es", "fr", "de"]),
    }


# --- ARRAY COLUMNS ---

def generate_tags(count: int = None) -> List[str]:
    """Generate array of tags."""
    if count is None:
        count = random.randint(1, 5)
    return [fake.word() for _ in range(count)]


def generate_uuid_array(existing_ids: List[str], count: int = None) -> List[str]:
    """Generate array of UUIDs from existing IDs."""
    if count is None:
        count = random.randint(1, min(5, len(existing_ids)))
    return random.sample(existing_ids, min(count, len(existing_ids)))


# --- FOREIGN KEY COLUMNS ---

def generate_foreign_key(existing_ids: List[str]) -> Optional[str]:
    """Generate a foreign key from existing IDs."""
    if not existing_ids:
        return None
    return random.choice(existing_ids)


# =============================================================================
# ROW GENERATOR
# =============================================================================

def generate_row(existing_ids: Dict[str, List[str]] = None) -> Dict[str, Any]:
    """
    Generate a single row of data.

    Args:
        existing_ids: Dictionary mapping foreign key columns to lists of existing IDs

    Returns:
        Dictionary representing a single row
    """
    if existing_ids is None:
        existing_ids = {}

    created_at = generate_created_at()

    row = {
        "id": generate_id(),

        # =====================================================================
        # DOMAIN COLUMNS - Customize for your table
        # =====================================================================
        # "title": generate_title(),
        # "description": generate_description(),
        # "rating": generate_rating(),
        # "price": generate_price(),
        # "is_active": generate_boolean(0.9),
        # "status": generate_status(["draft", "published", "archived"]),
        # "genre_id": generate_foreign_key(existing_ids.get("genre_id", [])),
        # "metadata": generate_metadata(),
        # "tags": generate_tags(),
        # =====================================================================

        # Timestamps
        "created_at": created_at,
        "updated_at": generate_updated_at(created_at),

        # Sync tracking (REQUIRED - do not modify)
        "sync_status": "pending",
        "sync_timestamp": None,
        "sync_error": None,
    }

    return row


# =============================================================================
# FOREIGN KEY HELPERS
# =============================================================================

async def get_foreign_key_ids(conn: asyncpg.Connection) -> Dict[str, List[str]]:
    """
    Fetch existing IDs for foreign key columns.

    Add queries for each foreign key reference in your table.
    """
    ids = {}

    # Example: Get genre IDs
    # rows = await conn.fetch("SELECT id FROM genres WHERE sync_status = 'synced' LIMIT 1000")
    # ids["genre_id"] = [str(row["id"]) for row in rows]

    # Example: Get user IDs
    # rows = await conn.fetch("SELECT id FROM users LIMIT 1000")
    # ids["user_id"] = [str(row["id"]) for row in rows]

    return ids


# =============================================================================
# SEEDING FUNCTIONS
# =============================================================================

async def seed(
    count: int,
    db_url: str,
    clear: bool = False,
    batch_size: int = DEFAULT_BATCH_SIZE
) -> int:
    """
    Seed the table with generated data.

    Args:
        count: Number of rows to generate
        db_url: PostgreSQL connection URL
        clear: Whether to clear existing data first
        batch_size: Batch size for inserts

    Returns:
        Number of rows inserted
    """
    conn = await asyncpg.connect(db_url)

    try:
        # Optionally clear existing data
        if clear:
            await conn.execute(f"TRUNCATE TABLE {TABLE_NAME} CASCADE")
            print(f"✓ Cleared existing data from {TABLE_NAME}")

        # Get existing foreign key references
        existing_ids = await get_foreign_key_ids(conn)

        # Check if we have required foreign keys
        # if not existing_ids.get("genre_id"):
        #     print("⚠ Warning: No genres found. Run genres_seeder.py first.")

        # Generate and insert in batches
        total_inserted = 0

        for batch_start in range(0, count, batch_size):
            current_batch_size = min(batch_size, count - batch_start)

            # Generate batch of rows
            rows = [generate_row(existing_ids) for _ in range(current_batch_size)]

            # Prepare for batch insert
            columns = list(rows[0].keys())
            values = [tuple(row[col] for col in columns) for row in rows]

            # Build INSERT statement
            placeholders = ', '.join(f'${i+1}' for i in range(len(columns)))
            insert_sql = f"""
                INSERT INTO {TABLE_NAME} ({', '.join(columns)})
                VALUES ({placeholders})
            """

            # Execute batch insert
            await conn.executemany(insert_sql, values)

            total_inserted += current_batch_size
            print(f"  Progress: {total_inserted}/{count} rows inserted")

        # Log seeding operation
        await conn.execute(
            """
            INSERT INTO _sync_log (table_name, operation, status, rows_processed, completed_at)
            VALUES ($1, 'seed', 'success', $2, now())
            """,
            TABLE_NAME, total_inserted
        )

        print(f"✓ Seeded {total_inserted} rows into {TABLE_NAME}")
        return total_inserted

    except Exception as e:
        # Log error
        await conn.execute(
            """
            INSERT INTO _sync_log (table_name, operation, status, error_message, completed_at)
            VALUES ($1, 'seed', 'error', $2, now())
            """,
            TABLE_NAME, str(e)
        )
        print(f"✗ Error seeding {TABLE_NAME}: {e}")
        raise

    finally:
        await conn.close()


async def sync_to_remote():
    """Sync seeded data to remote Supabase."""
    try:
        # Import sync manager (relative import)
        from sync_manager import sync_table
        await sync_table(TABLE_NAME)
        print(f"✓ Synced {TABLE_NAME} to remote Supabase")
    except ImportError:
        print("⚠ sync_manager not found. Skipping sync.")
    except Exception as e:
        print(f"✗ Error syncing: {e}")


# =============================================================================
# CLI
# =============================================================================

def main():
    parser = argparse.ArgumentParser(
        description=f"Seed {TABLE_NAME} table with generated data"
    )
    parser.add_argument(
        "--count",
        type=int,
        default=DEFAULT_COUNT,
        help=f"Number of rows to generate (default: {DEFAULT_COUNT})"
    )
    parser.add_argument(
        "--clear",
        action="store_true",
        help="Clear existing data before seeding"
    )
    parser.add_argument(
        "--sync",
        action="store_true",
        help="Sync to remote Supabase after seeding"
    )
    parser.add_argument(
        "--db-url",
        default=DATABASE_URL,
        help="PostgreSQL connection URL"
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=DEFAULT_BATCH_SIZE,
        help=f"Batch size for inserts (default: {DEFAULT_BATCH_SIZE})"
    )

    args = parser.parse_args()

    print(f"\n{'='*60}")
    print(f"Seeding: {TABLE_NAME}")
    print(f"Count: {args.count}")
    print(f"{'='*60}\n")

    # Run seeder
    asyncio.run(seed(
        count=args.count,
        db_url=args.db_url,
        clear=args.clear,
        batch_size=args.batch_size
    ))

    # Optionally sync to remote
    if args.sync:
        print(f"\n{'='*60}")
        print("Syncing to remote...")
        print(f"{'='*60}\n")
        asyncio.run(sync_to_remote())

    print(f"\n{'='*60}")
    print("Done!")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
