"""
Edge Functions module for Supabase CRUD Engine.
Helpers for Supabase Edge Functions (Deno-based serverless functions).
"""

import subprocess
import json
from pathlib import Path
from typing import Optional
from dataclasses import dataclass

from .config import Config


@dataclass
class EdgeFunction:
    """Represents a Supabase Edge Function."""
    name: str
    path: Path
    deployed: bool = False
    version: Optional[str] = None


class EdgeFunctions:
    """Manager for Supabase Edge Functions."""

    def __init__(self, config: Config):
        self.config = config
        self.functions_path = self.config.project_root / 'supabase' / 'functions'

    def list_local_functions(self) -> list[EdgeFunction]:
        """List all local edge functions."""
        if not self.functions_path.exists():
            return []

        functions = []
        for func_dir in self.functions_path.iterdir():
            if func_dir.is_dir() and not func_dir.name.startswith('_'):
                index_file = func_dir / 'index.ts'
                if index_file.exists():
                    functions.append(EdgeFunction(
                        name=func_dir.name,
                        path=func_dir,
                        deployed=False
                    ))

        return functions

    def list_deployed_functions(self) -> list[str]:
        """List deployed edge functions using Supabase CLI."""
        try:
            result = subprocess.run(
                ['supabase', 'functions', 'list', '--project-ref', self._get_project_ref()],
                capture_output=True,
                text=True,
                timeout=30
            )

            if result.returncode != 0:
                return []

            # Parse output (format varies by CLI version)
            functions = []
            for line in result.stdout.strip().split('\n')[1:]:  # Skip header
                if line.strip():
                    parts = line.split()
                    if parts:
                        functions.append(parts[0])

            return functions

        except Exception as e:
            print(f"Failed to list deployed functions: {e}")
            return []

    def _get_project_ref(self) -> str:
        """Extract project reference from Supabase URL."""
        url = self.config.supabase_url
        # https://abcdefghij.supabase.co -> abcdefghij
        if '.supabase.co' in url:
            return url.split('//')[1].split('.')[0]
        return ''

    def deploy_function(self, function_name: str) -> bool:
        """Deploy a single edge function."""
        try:
            result = subprocess.run(
                [
                    'supabase', 'functions', 'deploy', function_name,
                    '--project-ref', self._get_project_ref()
                ],
                capture_output=True,
                text=True,
                timeout=120
            )

            if result.returncode != 0:
                print(f"Deploy failed: {result.stderr}")
                return False

            return True

        except Exception as e:
            print(f"Deploy error: {e}")
            return False

    def deploy_all(self) -> tuple[int, int]:
        """Deploy all local functions. Returns (deployed, failed) counts."""
        functions = self.list_local_functions()
        deployed = 0
        failed = 0

        for func in functions:
            print(f"  Deploying: {func.name}")
            if self.deploy_function(func.name):
                deployed += 1
                print(f"    Deployed successfully")
            else:
                failed += 1
                print(f"    FAILED")

        return deployed, failed

    def create_function_template(self, name: str, description: str = '') -> Path:
        """Create a new edge function from template."""
        func_dir = self.functions_path / name
        func_dir.mkdir(parents=True, exist_ok=True)

        # Create index.ts
        index_content = f'''// Edge Function: {name}
// {description}
// Generated by claude-product-cycle CRUD engine

import {{ serve }} from "https://deno.land/std@0.168.0/http/server.ts"
import {{ createClient }} from "https://esm.sh/@supabase/supabase-js@2"

const corsHeaders = {{
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}}

serve(async (req) => {{
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {{
    return new Response('ok', {{ headers: corsHeaders }})
  }}

  try {{
    // Create Supabase client
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      {{
        global: {{
          headers: {{ Authorization: req.headers.get('Authorization')! }},
        }},
      }}
    )

    // Your logic here
    const data = {{ message: 'Hello from {name}!' }}

    return new Response(
      JSON.stringify(data),
      {{
        headers: {{ ...corsHeaders, 'Content-Type': 'application/json' }},
        status: 200,
      }}
    )
  }} catch (error) {{
    return new Response(
      JSON.stringify({{ error: error.message }}),
      {{
        headers: {{ ...corsHeaders, 'Content-Type': 'application/json' }},
        status: 400,
      }}
    )
  }}
}})
'''

        index_file = func_dir / 'index.ts'
        index_file.write_text(index_content)

        return func_dir

    def get_function_logs(self, function_name: str, limit: int = 50) -> str:
        """Get logs for an edge function."""
        try:
            result = subprocess.run(
                [
                    'supabase', 'functions', 'logs', function_name,
                    '--project-ref', self._get_project_ref(),
                    '--limit', str(limit)
                ],
                capture_output=True,
                text=True,
                timeout=30
            )

            return result.stdout if result.returncode == 0 else result.stderr

        except Exception as e:
            return f"Failed to get logs: {e}"
